# Site settings
title: Kite Software Development Kit
email: cdk-dev@cloudera.org
description: "An open source data API for Hadoop."
url: "http://kitesdk.org"

license_url: "http://www.apache.org/licenses/LICENSE-2.0.html"
github_url: "https://github.com/kite-sdk/kite"
issue_tracker_url: "https://issues.cloudera.org/browse/CDK"
mailing_list_url: "https://groups.google.com/a/cloudera.org/forum/#!forum/cdk-dev"
contributing_url: "https://github.com/kite-sdk/kite/wiki/How-to-contribute"
examples_url: "https://github.com/kite-sdk/kite-examples"

# version-specific
baseurl: "/docs/1.1.0"
version: "1.1.0"
javadoc_url: "/docs/1.1.0/apidocs/index.html"
jdiff_url: "/docs/1.1.0/jdiff/changes.html"

dataset-command: "kite-dataset"

# Build settings
include: ["./samples/"]
markdown: kramdown

kramdown:
  input: GFM
  coderay_line_numbers: table
  

